import * as fs from "fs";
import type Graph from "graphology";

const _CYPHER_IDENT_RE = /[^A-Za-z0-9_]/g;

/** Escape a string for safe embedding in a Cypher single-quoted literal. */
export function cypherEscape(s: string): string {
  // First normalise: drop NUL and other C0 control chars except tab, LF, CR.
  const normalized = Array.from(s).filter((ch) => ch >= " " || ch === "\t" || ch === "\n" || ch === "\r").join("");
  return normalized
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

/** Sanitise a value used in identifier position (node label / rel type).
 *
 * Cypher does not provide a way to escape `:Foo` label syntax, so we must
 * strip everything except [A-Za-z0-9_] and require the result to start
 * with a letter; otherwise we fall back to a safe constant.
 */
export function cypherLabel(raw: string, fallback: string): string {
  const cleaned = (raw ?? "").replace(_CYPHER_IDENT_RE, "");
  if (!cleaned || !cleaned[0].match(/[A-Za-z]/)) return fallback;
  return cleaned;
}

/** Export graph as Neo4j Cypher import script. */
export function toCypher(graph: Graph, outputPath: string): void {
  const lines = ["// Neo4j Cypher import - generated by /graphify", ""];

  for (const nodeId of graph.nodes()) {
    const data = graph.getNodeAttributes(nodeId);
    const label = cypherEscape((data["label"] as string) ?? nodeId);
    const nodeIdEsc = cypherEscape(nodeId);
    const rawFtype = (data["file_type"] as string) || "unknown";
    const ftype = cypherLabel(
      rawFtype.charAt(0).toUpperCase() + rawFtype.slice(1),
      "Entity",
    );
    lines.push(`MERGE (n:${ftype} {id: '${nodeIdEsc}', label: '${label}'});`);
  }
  lines.push("");

  graph.forEachEdge((_edge: string, attrs: Record<string, unknown>, u: string, v: string) => {
    const rawRel = (attrs["relation"] as string) || "RELATES_TO";
    const rel = cypherLabel(
      rawRel.toUpperCase(),
      "RELATES_TO",
    );
    const conf = cypherEscape((attrs["confidence"] as string) ?? "EXTRACTED");
    const uEsc = cypherEscape(u);
    const vEsc = cypherEscape(v);
    lines.push(
      `MATCH (a {id: '${uEsc}'}), (b {id: '${vEsc}'}) ` +
      `MERGE (a)-[:${rel} {confidence: '${conf}'}]->(b);`
    );
  });

  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
}
