import type { LanguageConfig } from "../types/language.js";

const EMPTY_CONFIG: Readonly<LanguageConfig> = {
  tsModule: "",
  tsLanguageFn: "language",
  classTypes: [],
  functionTypes: [],
  importTypes: [],
  callTypes: [],
  commentTypes: [],
  stringTypes: [],
  decoratorTypes: [],
  namespaceTypes: [],
  staticPropTypes: [],
  helperFnNames: [],
  containerBindMethods: [],
  eventListenerProperties: [],
  nameField: "name",
  nameFallbackChildTypes: [],
  bodyField: "body",
  bodyFallbackChildTypes: [],
  callFunctionField: "function",
  callAccessorNodeTypes: [],
  callAccessorField: "attribute",
  functionBoundaryTypes: [],
  functionLabelParens: true,
  docLanguage: "",
  chunking: false,
  binary: false,
};

export const LANGUAGE_CONFIGS: Readonly<Record<string, LanguageConfig>> = {
  python: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-python",
    classTypes: ["class_definition"],
    functionTypes: ["function_definition"],
    importTypes: ["import_statement", "import_from_statement"],
    callTypes: ["call"],
    commentTypes: ["comment"],
    stringTypes: ["string"],
    decoratorTypes: ["decorator"],
    callAccessorNodeTypes: ["attribute"],
    callAccessorField: "attribute",
    functionBoundaryTypes: ["function_definition"],
  },

  javascript: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-javascript",
    classTypes: ["class_declaration"],
    functionTypes: ["function_declaration", "method_definition"],
    importTypes: ["import_statement", "export_statement"],
    callTypes: ["call_expression", "new_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string", "template_string"],
    callAccessorNodeTypes: ["member_expression"],
    callAccessorField: "property",
    functionBoundaryTypes: ["function_declaration", "arrow_function", "method_definition"],
  },

  typescript: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-typescript",
    tsLanguageFn: "language_typescript",
    classTypes: [
      "class_declaration",
      "abstract_class_declaration",
      "interface_declaration",
      "enum_declaration",
      "type_alias_declaration",
    ],
    functionTypes: ["function_declaration", "method_definition"],
    importTypes: ["import_statement", "export_statement"],
    callTypes: ["call_expression", "new_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string", "template_string"],
    callAccessorNodeTypes: ["member_expression"],
    callAccessorField: "property",
    functionBoundaryTypes: ["function_declaration", "arrow_function", "method_definition"],
  },

  tsx: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-typescript",
    tsLanguageFn: "language_tsx",
    classTypes: [
      "class_declaration",
      "abstract_class_declaration",
      "interface_declaration",
      "enum_declaration",
      "type_alias_declaration",
    ],
    functionTypes: ["function_declaration", "method_definition"],
    importTypes: ["import_statement", "export_statement"],
    callTypes: ["call_expression", "new_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string", "template_string"],
    callAccessorNodeTypes: ["member_expression"],
    callAccessorField: "property",
    functionBoundaryTypes: ["function_declaration", "arrow_function", "method_definition"],
  },

  go: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-go",
    classTypes: [],
    functionTypes: ["function_declaration", "method_declaration"],
    importTypes: ["import_declaration"],
    callTypes: ["call_expression"],
    commentTypes: ["comment"],
    stringTypes: ["interpreted_string_literal", "raw_string_literal"],
    callAccessorNodeTypes: ["selector_expression"],
    callAccessorField: "field",
    functionBoundaryTypes: ["function_declaration", "method_declaration"],
  },

  rust: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-rust",
    classTypes: [],
    functionTypes: ["function_item"],
    importTypes: ["use_declaration"],
    callTypes: ["call_expression"],
    commentTypes: ["comment", "line_comment", "block_comment"],
    stringTypes: ["string_literal"],
    callAccessorNodeTypes: ["field_expression", "scoped_identifier"],
    callAccessorField: "field",
    functionBoundaryTypes: ["function_item"],
  },

  java: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-java",
    classTypes: ["class_declaration", "interface_declaration", "record_declaration"],
    functionTypes: ["method_declaration", "constructor_declaration"],
    importTypes: ["import_declaration"],
    callTypes: ["method_invocation", "object_creation_expression"],
    commentTypes: ["comment", "line_comment", "block_comment"],
    stringTypes: ["string_literal"],
    decoratorTypes: ["marker_annotation", "annotation"],
    callFunctionField: "name",
    callAccessorNodeTypes: [],
    functionBoundaryTypes: ["method_declaration", "constructor_declaration"],
  },

  c: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-c",
    classTypes: [],
    functionTypes: ["function_definition"],
    importTypes: ["preproc_include"],
    callTypes: ["call_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string_literal"],
    callAccessorNodeTypes: ["field_expression"],
    callAccessorField: "field",
    functionBoundaryTypes: ["function_definition"],
  },

  cpp: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-cpp",
    classTypes: ["class_specifier", "struct_specifier"],
    functionTypes: ["function_definition"],
    importTypes: ["preproc_include"],
    callTypes: ["call_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string_literal"],
    callAccessorNodeTypes: ["field_expression", "qualified_identifier"],
    callAccessorField: "field",
    functionBoundaryTypes: ["function_definition"],
  },

  groovy: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-groovy",
    classTypes: ["class_declaration", "interface_declaration"],
    functionTypes: ["method_declaration", "constructor_declaration"],
    importTypes: ["import_declaration"],
    callTypes: ["method_invocation"],
    callFunctionField: "name",
    callAccessorNodeTypes: [],
    functionBoundaryTypes: ["method_declaration", "constructor_declaration"],
  },

  ruby: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-ruby",
    classTypes: ["class"],
    functionTypes: ["method", "singleton_method"],
    importTypes: [],
    callTypes: ["call"],
    commentTypes: ["comment"],
    stringTypes: ["string"],
    callFunctionField: "method",
    callAccessorNodeTypes: [],
    nameFallbackChildTypes: ["constant", "scope_resolution", "identifier"],
    bodyFallbackChildTypes: ["body_statement"],
    functionBoundaryTypes: ["method", "singleton_method"],
  },

  c_sharp: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-c-sharp",
    classTypes: ["class_declaration", "interface_declaration"],
    functionTypes: ["method_declaration"],
    importTypes: ["using_directive"],
    callTypes: ["invocation_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string_literal"],
    callAccessorNodeTypes: ["member_access_expression"],
    callAccessorField: "name",
    bodyFallbackChildTypes: ["declaration_list"],
    functionBoundaryTypes: ["method_declaration"],
  },

  kotlin: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-kotlin",
    classTypes: ["class_declaration", "object_declaration"],
    functionTypes: ["function_declaration"],
    importTypes: ["import_header"],
    callTypes: ["call_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string_literal"],
    callFunctionField: "",
    callAccessorNodeTypes: ["navigation_expression"],
    callAccessorField: "",
    nameFallbackChildTypes: ["simple_identifier", "identifier"],
    bodyFallbackChildTypes: ["function_body", "class_body"],
    functionBoundaryTypes: ["function_declaration"],
  },

  scala: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-scala",
    classTypes: ["class_definition", "object_definition"],
    functionTypes: ["function_definition"],
    importTypes: ["import_declaration"],
    callTypes: ["call_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string"],
    callFunctionField: "",
    callAccessorNodeTypes: ["field_expression"],
    callAccessorField: "field",
    nameFallbackChildTypes: ["identifier"],
    bodyFallbackChildTypes: ["template_body"],
    functionBoundaryTypes: ["function_definition"],
  },

  swift: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-swift",
    classTypes: ["class_declaration", "protocol_declaration"],
    functionTypes: ["function_declaration", "init_declaration", "deinit_declaration", "subscript_declaration"],
    importTypes: ["import_declaration"],
    callTypes: ["call_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string"],
    callFunctionField: "",
    callAccessorNodeTypes: ["navigation_expression"],
    callAccessorField: "",
    nameFallbackChildTypes: ["simple_identifier", "type_identifier", "user_type"],
    bodyFallbackChildTypes: ["class_body", "protocol_body", "function_body", "enum_class_body"],
    functionBoundaryTypes: ["function_declaration", "init_declaration", "deinit_declaration", "subscript_declaration"],
  },

  php: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-php",
    tsLanguageFn: "language_php",
    classTypes: ["class_declaration"],
    functionTypes: ["function_definition", "method_declaration"],
    importTypes: ["namespace_use_clause"],
    callTypes: ["function_call_expression", "member_call_expression", "scoped_call_expression", "class_constant_access_expression"],
    commentTypes: ["comment"],
    stringTypes: ["string"],
    staticPropTypes: ["scoped_property_access_expression"],
    helperFnNames: ["config"],
    containerBindMethods: ["bind", "singleton", "scoped", "instance"],
    eventListenerProperties: ["listen", "subscribe"],
    callFunctionField: "function",
    callAccessorNodeTypes: ["member_call_expression"],
    callAccessorField: "name",
    nameFallbackChildTypes: ["name"],
    bodyFallbackChildTypes: ["declaration_list", "compound_statement"],
    functionBoundaryTypes: ["function_definition", "method_declaration"],
  },

  elixir: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-elixir",
  },

  lua: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-lua",
    functionTypes: ["function_declaration"],
    importTypes: ["variable_declaration"],
    callTypes: ["function_call"],
    callFunctionField: "name",
    callAccessorNodeTypes: ["method_index_expression"],
    callAccessorField: "name",
    nameFallbackChildTypes: ["identifier", "method_index_expression"],
    bodyFallbackChildTypes: ["block"],
    functionBoundaryTypes: ["function_declaration"],
  },

  dart: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-dart",
  },

  bash: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-bash",
  },

  julia: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-julia",
  },

  zig: {
    ...EMPTY_CONFIG,
    tsModule: "tree-sitter-zig",
  },
} as const;

export function getLanguageConfig(name: string): LanguageConfig | undefined {
  return LANGUAGE_CONFIGS[name];
}
